# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: John Kilpatrick
author: John Kilpatrick
tagline: John's site. A website about optics, computing and everything in between. # Shorter description
description: >- # Longer description
  The home of John Kilpatrick; A physics Ph.D. candidate with a passion for
  learning, normally involving something computers, electronics. Based in the
  UK.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rjkilpatrick.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Delimits end of snippet of start of post
excerpt_separator: "<!--more-->"

# permalink: pretty # /:category/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/

# Paginator settings
paginate: 10
paginate_path: "/blog/:num"

# Socials
social_links:
  # facebook: jekyll
  github: rjkilpatrick
  # instagram: jekyll
  linkedin: rjkilpatrick
  # twitter: rjkilpatrick1
  # youtube: jekyll
  docker: itsrig

# Build settings
markdown: kramdown

kramdown:
  math_engine: katex
  parse_block_html: true
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge

timezone: Europe/London

plugins:
  - jekyll-feed # RSS feed for posts
  - jekyll-sitemap # Sitemap creation for SEO
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

# Collections
collections:
  tagpages: # Cannot be 'tags'!
    output: true
    permalink: /tags/:path/

# Default settings for pages
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/default-graph-image.webp # Cannot be relative or svg

  # Set all posts as post type
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: John Kilpatrick
      category: "blog"
      links: true
      styles: ["post.css"]
      seo:
        type: BlogPosting
      latex: yes
  
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  
  - scope:
      path: ""
      type: "tagpages"
    values:
      layout: "tag"

# SEO settings
twitter:
  username: rjkilpatrick1
  card: summary

# logo: /assets/img/logo.svg

social:
  name: John Kilpatrick
  links:
    - https://github.com/rjklpatrick
    - https://linkedin.com/in/rjkilpatrick
    - https://gitlab.com/rjkilpatrick
    - https://twitter.com/rjkilpatrick1
    - https://emps.exeter.ac.uk/physics-astronomy/staff/rjk217/
    - https://orcid.org/0000-0001-5119-6355

lang: en_GB

# Custom list to exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - TODO.md
  - README.md
